#!/bin/bash
#  Kobol.io
#  Test Application Suite
#

INSTALL_PATH="$(dirname $0)/"
APP_NAME="Helios64 Test Suite"
APP_VERSION="0.1"

source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-cpu
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-sata
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-uSD
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-emmc
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-usb
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-typec
source "$INSTALL_PATH"../lib/helios64-testapp/helios64-submenu-status

init_env()
{
    # Kill all running fio
    pkill -f fio
    pkill -f stress-ng
    pkill -f glmark2

    # Reset CPU Freq
    helios64_cpu_freq_reset
}

restore_env()
{
    helios64_cpu_test_stop
    helios64_sata_stop_all 2>&1 1>/dev/null
    helios64_uSD_stop_all 2>&1 1>/dev/null
    helios64_emmc_stop_all 2>&1 1>/dev/null
    helios64_usb_stop_all 2>&1 1>/dev/null
    helios64_typec_stop_all 2>&1 1>/dev/null

    helios64_cpu_freq_restore
    clear
}

display_version()
{
    echo "$APP_NAME - Version $APP_VERSION"
    exit 0
}

start_all()
{
    helios64_menu_sata all
    helios64_menu_uSD all
    helios64_menu_emmc all
    helios64_menu_usb all
    helios64_menu_cpu
}

main()
{
    local returncode value

    DIALOG_OK=0
    DIALOG_CANCEL=1
    DIALOG_ESC=255

    if [[ "$ALL_TEST" = true ]]; then
        start_all
        EXTRAARGS="--default-item Status"
    fi

    ITEMS=()
    ITEMS+=( "CPU"      "Run CPU Stress"  )
    ITEMS+=( "SATA"     "Run SATA (J2-J6, J8)test >>" )
    ITEMS+=( "MicroSD"  "Run MicroSD (J14) test" )
    ITEMS+=( "eMMC"  	"Run eMMC (U39) test" )
    ITEMS+=( "USB"      "Run USB Storage (J1 & J13) test >>" )
    ITEMS+=( "TypeC"    "Run USB Type-C (J15) test >>" )
    ITEMS+=( "Status"   "Display test status" )

    returncode=0
    while test $returncode != $DIALOG_CANCEL && test $returncode != $DIALOG_ESC
    do
        exec 3>&1

        value=$(dialog --ascii-lines --title "$APP_NAME" \
            $EXTRAARGS \
            --ok-label "Select" --cancel-label "Exit" \
            --menu "\nSimple User Interface to exercise Helios64 components.\n\nPlease select which component to test or select \"Status\"\nto display test status." \
            18 60 20 "${ITEMS[@]}" \
            2>&1 1>&3)

        returncode=$?
        exec 3>&-

        case $value in
        	"CPU")
                helios64_menu_cpu
	        	;;
	        "SATA")
                helios64_menu_sata
	        	;;
	        "MicroSD")
                helios64_menu_uSD
	        	;;
	        "eMMC")
                helios64_menu_emmc
	        	;;
	        "USB")
                helios64_menu_usb
	        	;;
	        "TypeC")
                helios64_menu_typec
	        	;;
	        "Status")
                helios64_menu_status
	        	;;
        esac
        EXTRAARGS=""
    done
}

if [ "$#" -gt 0 ]; then
    OPTIONS=$(getopt -o "va" -l "version,all" -- "$@")
    eval set -- "$OPTIONS"

    while [ ! -z "$1" ]
    do
        case "$1" in
            -v | --version )
                display_version
                ;;
            -a | --all )
                ALL_TEST=true
                break
                ;;
            *)
                exit 1
                ;;
        esac

        shift
    done
fi

init_env
main
restore_env
