#!/bin/bash
helios64_emmc_state=off
helios64_emmc_list="emmc"
TASTORAGE_EXEC="tastorage64"

helios64_emmc_test_run()
{
    echo "Starting $1"
    $TASTORAGE_EXEC start $1
    helios64_emmc_state=on
    return 0
}

helios64_emmc_test_stop()
{
    echo "Stopping $1"
    $TASTORAGE_EXEC stop $1
    helios64_emmc_state=off
    return 0
}

helios64_emmc_stop_all()
{
    for stop in $helios64_emmc_list
    do
        helios64_emmc_test_stop $stop
    done
}

helios64_menu_emmc()
{
    if [[ $helios64_emmc_state = "off" ]]; then
        dialog --ascii-lines --title "Please wait" --infobox \
        "\nStarting eMMC test" 5 30
        helios64_emmc_test_run "emmc" 2>&1 1>/dev/null
        sleep 2
    else
        dialog --ascii-lines --title "Please wait" --infobox \
        "\nStopping eMMC test" 5 30
        helios64_emmc_test_stop "emmc" 2>&1 1>/dev/null
        sleep 2
    fi
}
