#!/bin/bash

WORKDIR="/run/helios64_test/status"
LOCKFILE="$WORKDIR/lock"

status_monitor()
{
    local devices prev_status dev index
    devices="ata1 ata2 ata3 ata4 ata5 microsd emmc usb1 usb2 usb3 usb4 dp cpu eth0 eth1"
    prev_status=()

    exec 200<$LOCKFILE
    flock -x 200

    for dev in $devices
    do
        if [[ $dev == "dp" ]]; then
            status=$(tagpu status)
        elif [[ $dev == "cpu" ]]; then
            status=$(helios64_cpu_test_status)
        elif [[ $dev == "eth0" ]]; then
            status=$(tanet status $dev)
        elif [[ $dev == "eth1" ]]; then
            status=$(tanet status $dev)
        else
            status=$(tastorage64 status $dev)
        fi

        # Workaround for tailboxbg, the file should contain at least 3 lines
        echo "$status" >> ${WORKDIR}/status-test-$dev.log
        echo "$status" >> ${WORKDIR}/status-test-$dev.log
        echo "$status" >> ${WORKDIR}/status-test-$dev.log
        sync
        prev_status+=("$status")
    done

    flock -u 200

    while [ true ]
    do
        index=0
        for dev in $devices
        do
            if [[ $dev == "dp" ]]; then
                status=$(tagpu status)
            elif [[ $dev == "cpu" ]]; then
        	    status=$(helios64_cpu_test_status)
        	elif [[ $dev == "eth0" ]]; then
        	    status=$(tanet status $dev)
        	elif [[ $dev == "eth1" ]]; then
        	    status=$(tanet status $dev)
            else
                status=$(tastorage64 status $dev)
            fi

            if [[ ${prev_status[index]} != $status ]]; then
                echo "$status" >> ${WORKDIR}/status-test-$dev.log
                sync
                prev_status[$index]="$status"
            fi

            ((index++))
        done

        sleep 1
    done
}

status_show()
{
    dialog  --ascii-lines --no-shadow \
        --begin 0 0 --title "Status: CPU" \
            --tailboxbg ${WORKDIR}/status-test-cpu.log 4 20 \
        --and-widget \
        --begin 4 0 --ascii-lines --title "Status: microSD" \
            --tailboxbg ${WORKDIR}/status-test-microsd.log 4 20 \
        --and-widget \
        --begin 8 0 --ascii-lines --title "Status: eMMC" \
            --tailboxbg ${WORKDIR}/status-test-emmc.log 4 20 \
        --and-widget \
        --begin 12 0 --ascii-lines --title "Status: eth0" \
            --tailboxbg ${WORKDIR}/status-test-eth0.log 4 20 \
        --and-widget \
        --begin 16 0 --ascii-lines --title "Status: eth1" \
            --tailboxbg ${WORKDIR}/status-test-eth1.log 4 20 \
        --and-widget \
        --begin 0 21 --ascii-lines --title "Status: ata1" \
            --tailboxbg ${WORKDIR}/status-test-ata1.log 4 20 \
        --and-widget \
        --begin 4 21 --ascii-lines --title "Status: ata2" \
            --tailboxbg ${WORKDIR}/status-test-ata2.log 4 20 \
        --and-widget \
        --begin 8 21 --ascii-lines --title "Status: ata3" \
            --tailboxbg ${WORKDIR}/status-test-ata3.log 4 20 \
        --and-widget \
        --begin 12 21 --ascii-lines --title "Status: ata4" \
            --tailboxbg ${WORKDIR}/status-test-ata4.log 4 20 \
        --and-widget \
        --begin 16 21 --ascii-lines --title "Status: ata5" \
            --tailboxbg ${WORKDIR}/status-test-ata5.log 4 20 \
        --and-widget \
        --begin 0 42 --ascii-lines --title "Status: usb1" \
            --tailboxbg ${WORKDIR}/status-test-usb1.log 4 20 \
        --and-widget \
        --begin 4 42 --ascii-lines --title "Status: usb2" \
            --tailboxbg ${WORKDIR}/status-test-usb2.log 4 20 \
        --and-widget \
        --begin 8 42 --ascii-lines --title "Status: usb3" \
            --tailboxbg ${WORKDIR}/status-test-usb3.log 4 20 \
        --and-widget \
        --begin 12 42 --ascii-lines --title "Status: Type-C Host" \
            --tailboxbg ${WORKDIR}/status-test-usb4.log 4 20 \
        --and-widget \
        --begin 16 42 --ascii-lines --title "Status: Type-C DP" \
            --tailboxbg ${WORKDIR}/status-test-dp.log 4 20 \
        --and-widget \
        --begin 20 0 --no-shadow --ascii-lines --ok-label "Return" --msgbox "" 3 62
}

helios64_menu_status()
{
    [[ -d $WORKDIR ]] || mkdir -p ${WORKDIR}
    # Disable CPU status
    #echo "N/A" >>${WORKDIR}/status-test-cpu.log
    exec 100>$LOCKFILE

    status_monitor &
    pid_monitor=$!
    sync
    sleep 2
    flock -w 10 100

    status_show

    kill $pid_monitor >/dev/null
    rm -rf ${WORKDIR}
}
