#!/bin/bash

helios64_sata_state[1]=off
helios64_sata_state[2]=off
helios64_sata_state[3]=off
helios64_sata_state[4]=off
helios64_sata_state[5]=off

helios64_sata_list="ata1 ata2 ata3 ata4 ata5"
TASTORAGE_EXEC="tastorage64"

helios64_sata_test_run()
{
    echo "Starting $1"
    $TASTORAGE_EXEC start $1
    return 0
}

helios64_sata_test_stop()
{
    echo "Stopping $1"
    $TASTORAGE_EXEC stop $1
    return 0
}

helios64_sata_stop_all()
{
    for stop in $helios64_sata_list
    do
        helios64_sata_test_stop $stop
    done
}

helios64_sata_test_apply()
{
    local list_stop list_start

    clear

    #set -x
    if [[ $# -eq 0 ]]; then
        return 0
    fi

    while (( "$#" )); do
        list_start=$(echo "$list_start $1")
        shift
    done

    # Get list of device to stop
    for stop in $helios64_sata_list
    do
        is_stop=1
        for start in $list_start
        do
            if [[ $stop = $start ]]; then
                is_stop=0
                break
            fi
        done

        [[ $is_stop -eq 1 ]] && list_stop=$(echo "$list_stop $stop")
    done

    # Stop test
    for stop in $list_stop
    do
        case $stop in
            "ata1")
               helios64_sata_state[1]=off
               ;;
            "ata2")
               helios64_sata_state[2]=off
               ;;
            "ata3")
               helios64_sata_state[3]=off
               ;;
            "ata4")
               helios64_sata_state[4]=off
               ;;
            "ata5")
               helios64_sata_state[5]=off
               ;;
        esac

        helios64_sata_test_stop $stop
    done

    # Start test
    for start in $list_start
    do
        case $start in
            "ata1")
               helios64_sata_state[1]=on
               ;;
            "ata2")
               helios64_sata_state[2]=on
               ;;
            "ata3")
               helios64_sata_state[3]=on
               ;;
            "ata4")
               helios64_sata_state[4]=on
               ;;
            "ata5")
               helios64_sata_state[5]=on
               ;;
        esac

        helios64_sata_test_run $start
    done
    #set +x

    return 0
}

helios64_sata_get_list()
{
    return 0
}


helios64_menu_sata()
{
    local returncode

    if [ "$1" = "all" ]; then
        helios64_sata_test_apply $helios64_sata_list
        return 0
    fi

    while true
    do
        exec 3>&1
        value=$(dialog --ascii-lines --ok-label "Apply" \
            --cancel-label "Return" \
            --checklist "Select SATA Port to test" \
            12 50 6 \
            "ata1" "Port 0 SATA1 (J3)/ M.2 SATA (J2)" ${helios64_sata_state[1]} \
            "ata2" "Port 1 SATA2 (J4)" ${helios64_sata_state[2]} \
            "ata3" "Port 2 SATA3 (J5)" ${helios64_sata_state[3]} \
            "ata4" "Port 3 SATA4 (J6)" ${helios64_sata_state[4]} \
            "ata5" "Port 4 SATA5 (J8)" ${helios64_sata_state[5]} \
            2>&1 1>&3)

        returncode=$?
        exec 3>&-

        [[ $returncode == $DIALOG_CANCEL || $returncode == $DIALOG_ESC ]] && clear && return 1

        helios64_sata_test_apply $value
    done
}
